packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true

catalog:
  "@arethetypeswrong/cli": 0.18.2
  "@arethetypeswrong/core": 0.18.2
  "@microsoft/api-extractor": 7.52.11
  "@react-three/drei": 10.7.7
  "@react-three/fiber": 9.6.1
  fast-check: 4.3.0
  publint: 0.3.15
  react: 19.1.1
  react-dom: 19.1.1
  three: 0.185.1
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 3.2.4

minimumReleaseAgeExclude:
  - '@lk-robotics/lds-core@0.1.0-rc.0'
  - '@lk-robotics/lds-product@0.1.0-rc.0'
  - '@lk-robotics/lds-robotics-ui@0.1.0-rc.0 || 0.1.0-rc.1'
  - '@lk-robotics/lds-theme@0.1.0-rc.0'
